name: igea_app
description: Segui lo scoiattolo

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1




environment:
  #sdk: ">=2.2.2 <3.0.0"
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.1
  firebase_storage: ^10.0.4
  firebase_auth: ^3.3.7 #^1.0.1
  firebase_analytics: ^9.1.0 #^8.0.2
  provider: ^5.0.0
  flutter_spinkit: ^4.1.1+1
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  #flutter_facebook_login: ^3.0.0 ##
  google_sign_in: ^5.2.4 
  flutter_staggered_grid_view: ^0.3.0
  circular_check_box: ^1.0.1
  rxdart: ^0.23.1
  auto_size_text: ^2.1.0
  json_annotation: ^4.0.0
  camera: ^0.5.8+2
  path_provider: ^2.0.1
  path:
  #device_preview: ^0.7.1
  cloud_functions: ^3.2.7
  firebase_messaging: ^11.2.6 #^9.0.0 
  flutter_local_notifications: ^5.0.0
  #url_launcher: ^5.4.11
  firebase_core: ^1.12.0 #^1.0.1
  #flutter_dialogflow: ^0.1.3
  # flutter_dialogflow_v2: ^0.3.2
  dialog_flowtter: ^0.3.0-nullsafety.0
  autocomplete_textfield: ^1.7.3
  flutter_holo_date_picker: ^0.2.1
  flutter_time_picker_spinner: ^1.0.6+1
  bubble: ^1.1.9+1
  http: ^0.13.0
  http_parser: ^4.0.0
  tuple: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.20.0-nullsafety.3
  fluttertoast: ^7.1.1
  lottie: ^1.0.1
  google_maps_flutter: ^2.0.11


dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.3
  build_runner: ^1.9.0
  animated_text_kit: ^2.2.0



flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true 
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/external/
   - assets/logo/
   - assets/icons/
   - assets/avatars/
   - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PassengersScript
      fonts:
        - asset: fonts/Passengers-Script.ttf
    - family: FilsonSoft
      fonts:
        - asset: fonts/Filson-Soft-W03-Regular.ttf
    - family: MarckScript
      fonts:
        - asset: fonts/MarckScript-Regular.ttf    
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Regular.ttf
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo/Cairo-Black.ttf
          weight: 900 
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Black.otf
    - family: Bold
      fonts:
        - asset: fonts/Gotham-Bold.otf
    - family: Book
      fonts:
        - asset: fonts/GothamBook.otf
    - family: Light
      fonts:
        - asset: fonts/Gotham-Light.otf
    - family: Myriad
      fonts:
        - asset: fonts/MyriadPro-Regular.otf
    
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages